### ISSUE TITLE
VertxConfigTestCase fails on Windows

### ISSUE THREAD

**Issue by gaol** [gaol/wildfly-vertx-extension#11]
[VertxConfigTestCase](https://github.com/gaol/wildfly-vertx-extension/blob/master/testsuite/integration/mini/src/test/java/org/wildfly/extension/vertx/test/mini/components/config/VertxConfigTestCase.java) fails on Windows with following exception:

The same for other tests which rely on resource resolve (FileResolverImpl from Vert.x).

```java
08:11:05,707 INFO  [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0010: Deployed "test-vertx-config.war" (runtime-name : "test-vertx-config.war")
08:11:06,054 ERROR [stderr] (vert.x-eventloop-thread-0) io.vertx.core.VertxException: Unable to unpack file at path 'vfs:/D:/a/wildfly-vertx-extension/wildfly-vertx-extension/testsuite/integration/mini/content/test-vertx-config.war/WEB-INF/classes/file-config.json'
08:11:06,054 ERROR [stderr] (vert.x-eventloop-thread-0) 	at io.vertx.core@4.2.6//io.vertx.core.file.impl.FileResolverImpl.unpackFromBundleURL(FileResolverImpl.java:361)
08:11:06,063 ERROR [stderr] (vert.x-eventloop-thread-0) Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
08:11:06,064 ERROR [stderr] (vert.x-eventloop-thread-0) 	at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
08:11:06,064 ERROR [stderr] (vert.x-eventloop-thread-0) 	at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:484)
08:11:06,064 ERROR [stderr] (vert.x-eventloop-thread-0) 	at java.base/java.io.File.getCanonicalPath(File.java:626)
08:11:06,064 ERROR [stderr] (vert.x-eventloop-thread-0) 	at io.vertx.core@4.2.6//io.vertx.core.file.impl.FileCache.fileNameCheck(FileCache.java:217)
```

When `FileCache.cacheFile(fileName)` is called from `FileResolverImpl.unpackFromBundleURL()`, the `fileName` in this `vfs://` case contains `D:/` in the path, which makes the path of `new File(getCacheDir(), fileName)` can not be resolved by the underline FileSystem.

jboss-vfs is the `vfs` URL protocol implementation, which can be resolved to a physical file in the real file system, I think it deserves it's own implementation in this extension project.

**Comment by gaol** [comment]
Fixed in https://github.com/gaol/wildfly-vertx-extension/commit/deafbf5331d8b11a3c4b9db600f96fc8609328cf
